name: Build packages for Linux

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-linux:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v5
            - name: update package index
              run: sudo apt update
            #- name: update or install required packages
            #  run: sudo apt-get install -y gcc libncurses5-dev libncursesw5-dev git make libarchive-tools curl
            - name: set up docker
              run: |
                sudo docker pull archlinux:base-devel
            - name: create pacman package on docker
              run: |
                sudo docker run -t -d --name=arch archlinux:base-devel /bin/bash
                sudo docker cp ./ arch:/termimg
                sudo docker exec arch sh /termimg/pkg/archonubuntu.sh
            - name: get pacman package from docker container
              run: sudo docker cp arch:/termimg/pkg ./archpkg
            - name: Arch package artifact
              uses: actions/upload-artifact@v4
              with:
                name: package-arch-linux
                path: archpkg